logoText = "Song Ou-Yang"
logoType = "short" # long, short
description = "Song Ou-Yang's site"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["light", "dark", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = false
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "main" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = "æ¬§é˜³æ¾"
email = "ouyangsong@shzu.edu.cn"
whoami = "åœ¨ç«™åšå£«å/å‰¯ä¸»ä»»åŒ»å¸ˆ"
bioImageUrl = ""
useGravatar = false ## è®¾ç½®ä¸ºfalseä¼šæ˜¾ç¤ºæˆ‘çš„å¤´åƒ
location = "æ–°ç–†, çŸ³æ²³å­"
organization = "çŸ³æ²³å­å¤§å­¦åŒ»å­¦é™¢ç¬¬ä¸€é™„å±åŒ»é™¢"
link = "https://swcyo.rbind.io/"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = true
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4","h5"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = "af43714f0d2bda327dfa276339b9db25"
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true


[socialOptions]
  email = "mailto://ouyangsong@shzu.edu.cn"
  github = "https://github.com/swcyo/Rblog"
  weibo = "https://weibo.com/swcyoyond"
  jianshu = "https://www.jianshu.com/u/c23f6285abcc"
  zhihu = "https://www.zhihu.com/people/swcyo"
  google-scholar = "https://scholar.google.com/citations?hl=zh-CN&pli=1&user=eTN286IAAAAJ"

[donationOptions]
  enable = false
  alipay = "" 
  wechat = "swcyoyond"
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = "weibo"
  username = "swcyoyond"

[[footerLinks]]
  name = "çŸ³æ²³å­å¤§å­¦"
  link = "http://www.shzu.edu.cn/"
[[footerLinks]]
  name = "çŸ³æ²³å­å¤§å­¦åŒ»å­¦é™¢ç¬¬ä¸€é™„å±åŒ»é™¢"
  link = "http://www.sdyfy.com.cn/"
[[footerLinks]]
  name = "æˆ‘çš„ç™¾åº¦å­¦æœ¯"
  link = "https://xueshu.baidu.com/scholarID/CN-BP74VAPJ"
[[footerLinks]]
  name = "æˆ‘çš„ORCID"
  link = "https://orcid.org/0000-0001-7962-2811"